FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r ./requirements.txt

# COPY . .

# RUN ['flask', 'db', 'upgrade']

# CMD [ "gunicorn", "-b 0.0.0.0:8000", "wsgi:app" ]