"""empty message

Revision ID: 88f9b914ee28
Revises: 98b24c263609
Create Date: 2019-06-18 11:42:10.397469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f9b914ee28'
down_revision = '98b24c263609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
