"""empty message

Revision ID: 98b24c263609
Revises: 9938d225c2b9
Create Date: 2019-06-17 18:51:05.676358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b24c263609'
down_revision = '9938d225c2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('autor_id', sa.Integer(), nullable=False))
    op.drop_constraint('todo_user_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'users', ['autor_id'], ['id'])
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_user_id_fkey', 'todo', 'users', ['user_id'], ['id'])
    op.drop_column('todo', 'autor_id')
    # ### end Alembic commands ###
