"""empty message

Revision ID: 9938d225c2b9
Revises: d121ae206cca
Create Date: 2019-06-17 18:31:46.727797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9938d225c2b9'
down_revision = 'd121ae206cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autors_performers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autors_performers',
    sa.Column('autor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], name='autors_performers_autor_id_fkey'),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], name='autors_performers_performer_id_fkey')
    )
    # ### end Alembic commands ###
