"""empty message

Revision ID: caaff0405fee
Revises: 81598e03a1f7
Create Date: 2019-06-22 16:35:46.416654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaff0405fee'
down_revision = '81598e03a1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'expiry_date')
    # ### end Alembic commands ###
