"""empty message

Revision ID: d121ae206cca
Revises: 
Create Date: 2019-06-14 17:30:08.689958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd121ae206cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autors_performers',
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], )
    )
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('todo_autor_id_fkey', 'todo', type_='foreignkey')
    op.drop_constraint('todo_performer_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'users', ['user_id'], ['id'])
    op.drop_column('todo', 'autor_id')
    op.drop_column('todo', 'performer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('performer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('todo', sa.Column('autor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_performer_id_fkey', 'todo', 'users', ['performer_id'], ['id'])
    op.create_foreign_key('todo_autor_id_fkey', 'todo', 'users', ['autor_id'], ['id'])
    op.drop_column('todo', 'user_id')
    op.drop_table('autors_performers')
    # ### end Alembic commands ###
